// chop pi extension - generated by `chop init --pi`, do not edit by hand.
// Intercepts bash tool calls and rewrites them through chop for output compression.
import { spawnSync } from "node:child_process";

const CHOP_BIN = "__CHOP_BIN__";

export default function (pi: any) {
  pi.on("tool_call", async (event: any) => {
    if (event.toolName !== "bash") return;

    const payload = JSON.stringify({
      hook_event_name: "PreToolUse",
      tool_name: "bash",
      tool_input: { command: event.input?.command },
    });

    let result;
    try {
      result = spawnSync(CHOP_BIN, ["hook", "--pi"], {
        input: payload,
        encoding: "utf8",
        timeout: 5000,
      });
    } catch {
      return;
    }

    if (!result || result.status !== 0 || !result.stdout) return;

    try {
      const out = JSON.parse(result.stdout);
      const updated = out?.hookSpecificOutput?.updatedInput?.command;
      if (updated) event.input.command = updated;
    } catch {
      // Not JSON (or empty) - passthrough, leave the command untouched.
    }
  });
}
