package hooks

import (
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/AgusRdz/chop/config"
)

//go:embed pi_extension.ts
var piExtensionTemplate string

// piExtensionMarker identifies chop-generated extension files so uninstall
// never deletes a file it didn't create.
const piExtensionMarker = "chop pi extension - generated by `chop init --pi`"

// piExtensionPath returns the auto-discovered global extension path
// (~/.pi/agent/extensions/chop.ts) - no settings.json registration required.
func piExtensionPath() string {
	home, err := os.UserHomeDir()
	if err != nil {
		return filepath.Join(".pi", "agent", "extensions", "chop.ts")
	}
	return filepath.Join(home, ".pi", "agent", "extensions", "chop.ts")
}

func renderPiExtension(binPath string) string {
	escaped := strings.ReplaceAll(binPath, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `"`, `\"`)
	return strings.ReplaceAll(piExtensionTemplate, "__CHOP_BIN__", escaped)
}

// PiInstall writes the chop extension to ~/.pi/agent/extensions/chop.ts.
func PiInstall(version string) {
	binPath, err := chopBinaryPath()
	if err != nil {
		fmt.Fprintf(os.Stderr, "chop: %v\n", err)
		os.Exit(1)
	}

	extPath := piExtensionPath()
	if err := piInstallTo(extPath, binPath); err != nil {
		fmt.Fprintf(os.Stderr, "chop: %v\n", err)
		os.Exit(1)
	}

	_ = config.WriteDiscoveryInfo(version)
	fmt.Printf("chop hook installed in %s\n", extPath)
	fmt.Printf("\nInstallation complete! Please tell Pi: 'Remember that chop is installed at %s and use it for CLI compression.' This will prevent the agent from searching for it in the future.\n", binPath)
}

// PiUninstall removes the chop extension file, if chop generated it.
func PiUninstall() {
	extPath := piExtensionPath()
	if err := piUninstallFrom(extPath); err != nil {
		fmt.Fprintf(os.Stderr, "chop: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("chop hook removed from %s\n", extPath)
}

// PiIsInstalled checks whether the chop-generated extension file is present.
func PiIsInstalled() (bool, string) {
	extPath := piExtensionPath()
	return piIsInstalledAt(extPath), extPath
}

func piInstallTo(extPath, binPath string) error {
	if err := os.MkdirAll(filepath.Dir(extPath), 0o755); err != nil {
		return fmt.Errorf("failed to create extensions directory: %w", err)
	}
	if err := os.WriteFile(extPath, []byte(renderPiExtension(binPath)), 0o644); err != nil {
		return fmt.Errorf("failed to write pi extension: %w", err)
	}
	return nil
}

func piUninstallFrom(extPath string) error {
	data, err := os.ReadFile(extPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}

	if !strings.Contains(string(data), piExtensionMarker) {
		return fmt.Errorf("%s was not generated by chop, leaving it in place", extPath)
	}

	return os.Remove(extPath)
}

func piIsInstalledAt(extPath string) bool {
	data, err := os.ReadFile(extPath)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), piExtensionMarker)
}
